sub1=int(input("Marks of subject 1: "))
sub2=int(input("Marks of subject 2: "))
sub3=int(input("Marks of subject 3: "))
sub4=int(input("Marks of subject 4: "))
sub5=int(input("Marks of subject 5: "))
avg=(sub1+sub2+sub3+sub4+sub5)/5
cgpa=avg/10
if(cgpa>0)&(cgpa<=3.4):
    grade="F"
elif(cgpa>3.4)&(cgpa<=5):
    grade="C+"
elif(cgpa>5)&(cgpa<=6):
    grade="B"
elif(cgpa>6)&(cgpa<=7):
    grade="B+"
elif(cgpa>7)&(cgpa<=8):
    grade="A"
elif(cgpa>8)&(cgpa<=9):
    grade="A+"
elif(cgpa>9)&(cgpa<=10):
    grade="O"
print("grade= ",grade)